### ISSUE TITLE
install instructions incorrect or lack information 

### ISSUE THREAD

**Issue by temeyers** [krvarma/HomeKit-and-Particle-Photon#1]
these install instructions make no sense i can figure it out ... i can get homebridge to work in its default state and i can get HAP-NodeJS to run in its default state, however this here doesn't say where to put the Particle.js file and it also says to run node app.js ... there is no app.js in homebridge or hap-nodejs or in this zip file so none of this makes any sense at all if i run home bridge with the config.json setup per the instructions i get this 

No plugins found. See the README for information on installing plugins.
## Loaded config.json with 0 accessories and 1 platforms.

Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:74
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:74:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:185:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)

**Comment by krvarma** [comment]
@temeyers, for this sample a previous version of H?omebridge was used. Recently Homebridge is updated and structure is chaned. I am updating the sample using the current version of Homebridge, please be patient. May be in couple weeks I will update the sample.

The particle.js file should be copied to Accessory folder as described in the installation instruction point #2 and modify the config. To start Homebridge, simply after installing the it simply run the command 'homebridge'. It is described in the README of Homebridge.

**Comment by temeyers** [comment]
I see ... Thank you very much for that info, my biggest problem I see is that the particle.js going into this accessory folder is my issue does this new homebridge lack the accessory folder ? I don't see any accessory folder at all but when I do an npm install -g homebridge-wemo for instance it does show a new folder in the homebridge directory... There isn't any accessory folder that I see to put the particle.js into ... I know hap-Nodejs has an accessory folder but of coarse putting it in there and running node.js doesn't work nor is it supposed to ... What am I missing about setting up homebridge and putting the particle.js In the right place, any help is highly appreciated I have a fun project I am really trying to get going but I do understand everything takes time

**Comment by krvarma** [comment]
Sure, but to install the new plugin I have to modify and upload my particle.js accessory to NPM. I will make it available ASAP. As a temporary solution, you can download previous version of the Homebridge and try.

**Comment by temeyers** [comment]
Do you know what version works I will try

**Comment by temeyers** [comment]
any luck on this or is there anything i could do to assist? im obsessing over getting the photon to do something other than turn on a light with the homebridge-http plugin

**Comment by krvarma** [comment]
@temeyers, alomst finished, may take couple of days to update on npm. I will make it faster, sorry for the delay :(.

**Comment by rudyv** [comment]
@krvarma Hope all goes fine with the porting to the new version of homebridge, I managed to install the new version and now I'm looking forward to your adaptation to this new homebridge. So keep up the good work and I hope that you have it going soon. If I can help you with testing then I'm more then willing to do so.
Take care,
Rudy

**Comment by Daandamhuis** [comment]
@krvarma How are you doing with getting the npm up-to-date, i'm very interested! If you need so help, let me know!

**Comment by krvarma** [comment]
@Daandamhuis, as you know this is a specific example of using HomeBridge and Particle. After some thought I am working on a Generic Particle accessory instead of a specific example. I think this is better  than a specific solutions. 

What I am thinking is create a generic NPM module, users can install this module and make necessary changes to the Config file like calling a function, listening for a SSE, read a variable, etc... and make it according to their own requirements.

Meanwhile you can use the old example by installing the old version, please follow this instatructions to install it (this is specific to Windows, but I think it will work for other platforms also, not sure).

**Comment by Nedervino** [comment]
Any estimates on when the updated npm module will be available? As I would like to keep the current version of homebridge for compatibility with my other scripts. Good luck!

**Comment by temeyers** [comment]
I think he stopped working on it he doesn't reply anymore

**Comment by krvarma** [comment]
@Nedervino, @temeyers I don't have a specific date now. What I am doing is a generic Particle class that can be used to interact with HomeBridge. But now I have a very important deadline, I couldn't get time to work on it. I hope can resume next week, will keep you updated.

As I mentioned above this is a specific example which in not appropriate for NPM module, that is the reason I am working on a generic module.

**Comment by cmegens** [comment]
any news on the plugin? Or can you share your work so far on github, so others can have a crack at it?

**Comment by temeyers** [comment]
Hasn't worked in almost a year it feels like ... I think he gave up

**Comment by krvarma** [comment]
Sorry for the long delay, I will share all my code this weekend or next so you guys can work on that. The delay was not intentional but because of some tight deadlines.

**Comment by rudyv** [comment]
HI Krishnaraj,

Any news from your side ? It would be great to get this npm version ready. I'm willing to help in testing, just let me know :+1:

**Comment by krvarma** [comment]
I have create a new repo [https://github.com/krvarma/homebridge-particle](https://github.com/krvarma/homebridge-particle) and uploaded all code. I am preparing a README file and will checkin this weekend.

The plugin now supports Light, Temperature Sensor, Humidity Sensor and Light Sensor as of now. More on tha way.

To install the plugin run `npm install -g homebridge-particle`

**Comment by rudyv** [comment]
Great, it installed OK. I will test it in the weekend.
Thanks

**Comment by JoniSykes** [comment]
Hi Thread!
Thanks for all the work you've done on this guys. 
I have a few issues with my install. 
Firstly: I'm using a Core not a Photon but I doubt this makes a difference.
So I've copied the config and Accesory files onto my mac and they work fine. 
Unfortunately the firmware is not fine however. I get quite a few errors about types and uints that I really don't understand. Could you by any chance attempt to re-flash a photon or core with the code and see if you have any issues?

Thanks.
